name: Build-CI

on:
  push:
    branches:
      - main
    tags:
      - '!v*'
  pull_request:

env:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
    - name: Build .NET
      run: dotnet build --configuration Release
    - name: Test .NET
      run: dotnet test --no-build --configuration Release
